### ISSUE TITLE
Design Doc Review #2 - Sample State

### ISSUE THREAD

**Issue by mmcnulty20** [ligokdoon/Suro#2]
## Sample State
- [x] Ensure keys are camelCased and not snake_cased.
- [x] Last name column is present in schema but not the state - why is that
- [x] Clearly specify what `carIDs` refers to (I assume cars that user owns)
- [x] Should distinguish `bookingId`s for bookings you are hosting vs bookings you made, assuming a user can have both.
- [x] Advocate for why you include both `hostId` and `carId` in bookings, and both `bookingID` and `carID` in reviews.

**Comment by wilsonli117** [comment]
## Sample State

- Replaced snack_cased keys with camelCased keys

- Added lastName key to user objects in users slice of state.

- Changed carIDs key to CarsOwnedIDs.

- Added bookingAsHostIDs key to user objects in users slice of state.

- There is both a userID and hostID in bookings because bookings will be nested within a user. The only way to see bookings is through "/users/:id/bookings".
