### ISSUE TITLE
Design Doc Review #3 - Frontend and Backend Routes

### ISSUE THREAD

**Issue by mmcnulty20** [ligokdoon/Suro#3]
## Backend Routes
- [x] No ability to edit or delete a user
- [x] When would you make a GET request to features? (I agree with the choice, though)
- [x] What would be an example of a feature that isn't 'core'? Why would this behavior be preferable over including the feature in the description, for example?
## Frontend Routes
- [x] From what I can tell these look good - we'll need to have a 1-on-1 soon to discuss Turo in general though.

**Comment by wilsonli117** [comment]
## Backend Routes

- Added backend routes to edit user and delete user. Also added frontend routes for '/users/:id/edit'.

- The idea is to immediately fetch all features, first ~25 IDs, as preloaded state. Which would be less expensive than separate queries for features when rendering car show pages. This will also to allow users to search by features.

- The initial idea was to allow users to input custom features when listing their car, but after some consideration, the description is a better place for this information to be displayed on. Removed create, update, delete actions from features controller because there will be no custom features.

## Frontend Routes

- As previously discussed, I will get screen-grabs of the car listing process and what it looks like from the perspective of a host. I will also get screen-grabs of the booking process and what an active booking looks like.

**Comment by mmcnulty20** [comment]
Great work on these revisions/explanations! :)
